# -*- coding: utf-8 -*-

class CVI_2000():

    def __init__(self):

        self.svid = 2000
        self.language = "JAVA"
        self.author = ""
        self.vulnerability = "XXE"
        self.description = "XML external entity injection"
        #Generated by data input and parsing in XML format

        # status
        self.status = True

        # 部分配置
        self.match_mode = "function-param-regex"
        self.match = "dombuilder\.parse|XMLStreamReader|SAXParser|SAXBuilder|SAXReader|SchemaFactory|Unmarshaller|XPathExpression|SAXSource|TransformerFactory|SAXTransformerFactory"
        #Functions that might parse xml
        self.vul_function = None

    def main(self, regex_string):
        pass